"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path: Path) -> None:
    """
    Загружает переменные окружения из .env (без внешних зависимостей).
    """
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key and value and key not in os.environ:
            os.environ[key] = value


_load_env_file(BASE_DIR / ".env")


def _env_bool(name: str, *, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "y", "on"}


def _env_csv(name: str, *, default: str = "") -> list[str]:
    return [part.strip() for part in os.environ.get(name, default).split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
# Production: DJANGO_SETTINGS_MODULE=config.settings_prod (см. PRODUCTION.md).

# SECURITY WARNING: keep the secret key used in production secret!
# Для локальной разработки используем env (а если не задано — безопасный dev-вариант).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS", default="127.0.0.1,localhost")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_htmx',
    # Local apps
    'core.apps.CoreConfig',
    'scenarios',
    'calculations',
    'support.apps.SupportConfig',
]

AUTH_USER_MODEL = "core.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # htmx support
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.breadcrumbs',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

USE_POSTGRES = os.environ.get("USE_POSTGRES", "false").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
}

# Для тестов по умолчанию используем SQLite, чтобы не требовать прав CREATEDB
# и внешнего доступа к Postgres.
if any(arg in {"test", "pytest"} for arg in sys.argv):
    USE_POSTGRES = False

if USE_POSTGRES:
    postgres_password = os.environ.get("POSTGRES_PASSWORD")
    if not postgres_password:
        raise RuntimeError("POSTGRES_PASSWORD is required when USE_POSTGRES=true")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get("POSTGRES_DB", "tariff_equlizer"),
            'USER': os.environ.get("POSTGRES_USER", "tariff_equlizer"),
            'PASSWORD': postgres_password,
            'HOST': os.environ.get("POSTGRES_HOST", "127.0.0.1"),
            'PORT': os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPPORT_MAX_ATTACHMENT_SIZE = 10 * 1024 * 1024  # 10 MB
SUPPORT_ALLOWED_ATTACHMENT_EXTENSIONS = {
    '.pdf', '.xlsx', '.xls', '.png', '.jpg', '.jpeg', '.docx', '.zip', '.csv', '.txt',
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

######################################################################
# Auth redirects
######################################################################

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/"

######################################################################
# Route mart (parquet cache on disk)
######################################################################

ROUTE_MART_CACHE_DIR = os.environ.get(
    "ROUTE_MART_CACHE_DIR",
    str(BASE_DIR / "cache" / "route_mart"),
)

SCENARIO_COMPUTE_CACHE_DIR = os.environ.get(
    "SCENARIO_COMPUTE_CACHE_DIR",
    str(BASE_DIR / "cache" / "scenario_compute"),
)

ROUTE_MASK_CACHE_DIR = os.environ.get(
    "ROUTE_MASK_CACHE_DIR",
    str(BASE_DIR / "cache" / "route_masks"),
)

######################################################################
# Cache (scenario effects snapshots)
######################################################################

_redis_url = os.environ.get("REDIS_URL", "").strip()
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "tariff-equlizer",
        }
    }
