# Generated by Django 5.0.8 on 2026-02-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_id'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='scenarios.scenario', verbose_name='Активный сценарий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
