# Generated by Django 5.0.8 on 2026-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoGroup',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Группа груза',
                'verbose_name_plural': 'Группы груза',
                'ordering': ['position', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
