# Generated by Django 5.0.8 on 2026-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cargogroup_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailRoad',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Железная дорога',
                'verbose_name_plural': 'Железные дороги',
                'ordering': ['code'],
            },
        ),
    ]
