# Generated by Django 6.0.2 on 2026-03-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Код ETSNG')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('cargo_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='core.cargogroup', verbose_name='Группа груза')),
            ],
            options={
                'verbose_name': 'Груз (ETSNG)',
                'verbose_name_plural': 'Грузы (ETSNG)',
                'ordering': ['code'],
            },
        ),
    ]
