# Generated by Django 5.0.8 on 2026-03-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='railroad',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='railroad',
            name='direction',
            field=models.CharField(blank=True, max_length=50, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
