# Generated by Django 5.0.8 on 2026-03-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_railroad_country_railroad_direction_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('type', models.CharField(max_length=50, verbose_name='Тип региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['full_name', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('esr_code', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Код ЕСР')),
                ('short_name', models.CharField(max_length=150, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'ordering': ['esr_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('full_name', 'type'), name='uniq_region_full_name_type'),
        ),
        migrations.AddField(
            model_name='station',
            name='railroad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='core.railroad', verbose_name='Железная дорога'),
        ),
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='core.region', verbose_name='Регион'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['short_name'], name='station_short_name_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['railroad'], name='station_railroad_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['region'], name='station_region_idx'),
        ),
    ]
