# Generated by Django 5.0.8 on 2026-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_region_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='full_name_search',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='short_name_search',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='type_search',
            field=models.CharField(db_index=True, default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='station',
            name='full_name_search',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='short_name_search',
            field=models.CharField(db_index=True, default='', editable=False, max_length=150),
        ),
    ]
