# Generated by Django 5.0.8 on 2026-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_region_full_name_search_region_short_name_search_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name_search', models.CharField(db_index=True, default='', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Тип сообщения',
                'verbose_name_plural': 'Типы сообщения',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name_search', models.CharField(db_index=True, default='', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Тип отправки',
                'verbose_name_plural': 'Типы отправки',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WagonKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name_search', models.CharField(db_index=True, default='', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Род вагона',
                'verbose_name_plural': 'Роды вагонов',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagetype',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uniq_messagetype_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='shipmenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uniq_shipmenttype_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='wagonkind',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uniq_wagonkind_code_nonempty'),
        ),
    ]
