# Generated by Django 5.0.8 on 2026-03-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_messagetype_shipmenttype_wagonkind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название набора')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код набора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Набор маршрутов',
                'verbose_name_plural': 'Наборы маршрутов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_holding', models.CharField(blank=True, max_length=255, verbose_name='Холдинг грузоотправителя')),
                ('shipper', models.CharField(blank=True, max_length=255, verbose_name='Грузоотправитель')),
                ('traffic_kind', models.CharField(blank=True, max_length=100, verbose_name='Вид перевозки (vid)')),
                ('polygon', models.CharField(blank=True, max_length=100, verbose_name='Полигон')),
                ('route_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ключевой код маршрута')),
                ('distance_loaded_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расстояние гружёный рейс, км')),
                ('distance_empty_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расстояние порожний рейс, км')),
                ('load_tons_per_wagon', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Загрузка в вагон, т')),
                ('empty_wagon_return_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Возврат порожних вагонов, %')),
                ('delivery_time_loaded_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки гружёный рейс, сут')),
                ('delivery_time_empty_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки порожний рейс, сут')),
                ('delivery_time_ops_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки погр./выгр., сут')),
                ('rate_per_wagon_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ставка на вагон, руб./вагон/сут')),
                ('rzd_cost_loaded_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Расходы РЖД, гружёный пробег, руб./т')),
                ('rzd_cost_empty_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Расходы РЖД, порожний пробег, руб./т')),
                ('rzd_cost_total_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Расходы РЖД, итого, руб./т')),
                ('operators_cost_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Расходы операторов, руб./т')),
                ('transshipment_cost_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Расходы на перевалку, руб./т')),
                ('excise_or_duty_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Акциз/пошлина, руб./т')),
                ('transport_total_cost_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общие транспортные расходы, руб./т')),
                ('production_cost_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Себестоимость добычи/производства, руб./т')),
                ('total_cost_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общие расходы, руб./т')),
                ('market_price_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Рыночная цена, руб./т')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.cargo', verbose_name='Груз')),
                ('destination_railroad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_routes', to='core.railroad', verbose_name='Дорога назначения')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_routes', to='core.station', verbose_name='Станция назначения')),
                ('message_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.messagetype', verbose_name='Тип сообщения')),
                ('origin_railroad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_routes', to='core.railroad', verbose_name='Дорога отправления')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_routes', to='core.station', verbose_name='Станция отправления')),
                ('shipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.shipmenttype', verbose_name='Тип отправки')),
                ('wagon_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.wagonkind', verbose_name='Род вагона')),
                ('route_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.routeset', verbose_name='Набор маршрутов')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['route_set', 'route_code', 'id'],
                'indexes': [models.Index(fields=['route_set', 'route_code'], name='route_set_code_idx'), models.Index(fields=['cargo'], name='route_cargo_idx'), models.Index(fields=['origin_station', 'destination_station'], name='route_stations_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('route_set', 'route_code'), name='uniq_route_set_route_code'),
        ),
    ]
