# Generated by Django 5.0.8 on 2026-03-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_routeset_route_route_uniq_route_set_route_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='destination_railroad',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origin_railroad',
        ),
    ]
