# Generated by Django 5.0.8 on 2026-03-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_route_destination_railroad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='traffic_kind',
        ),
    ]
