# Generated by Django 5.0.8 on 2026-03-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_route_traffic_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='polygon',
        ),
    ]
