# Generated by Django 6.0.2 on 2026-03-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_route_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='empty_wagon_return_pct',
        ),
    ]
