# Generated by Django 5.2.13 on 2026-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_route_empty_wagon_return_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='freight_charge_ths_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Провозная плата, тыс. руб.'),
        ),
        migrations.AddField(
            model_name='route',
            name='freight_turnover_bln_tkm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Грузооборот, млрд т·км'),
        ),
        migrations.AddField(
            model_name='route',
            name='transport_volume_mln_tons',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Объём перевозок, млн т'),
        ),
    ]
