# Generated by Django 6.0.2 on 2026-05-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_route_search_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetype',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Вид сообщения', 'verbose_name_plural': 'Виды сообщения'},
        ),
        migrations.AlterField(
            model_name='route',
            name='message_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.messagetype', verbose_name='Вид сообщения'),
        ),
    ]
