# Generated by Django 6.0.2 on 2026-05-24 17:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_route_shippers(apps, schema_editor):
    Route = apps.get_model("core", "Route")
    Shipper = apps.get_model("core", "Shipper")
    cache: dict[tuple, int] = {}

    for route in Route.objects.all().iterator():
        name = (getattr(route, "shipper_name", None) or "").strip()
        holding = (getattr(route, "shipper_holding", None) or "").strip()
        if not name:
            continue

        key = (0, "", name)
        shipper_id = cache.get(key)
        if shipper_id is None:
            shipper, _ = Shipper.objects.get_or_create(
                okpo=0,
                inn="",
                name=name,
                defaults={"holding": holding},
            )
            if holding and not shipper.holding:
                shipper.holding = holding
                shipper.save(update_fields=["holding"])
            shipper_id = shipper.pk
            cache[key] = shipper_id

        route.shipper_link_id = shipper_id
        route.save(update_fields=["shipper_link_id"])


def reverse_migrate_route_shippers(apps, schema_editor):
    Route = apps.get_model("core", "Route")
    for route in Route.objects.select_related("shipper_link").iterator():
        shipper = route.shipper_link
        if shipper is None:
            continue
        route.shipper_name = shipper.name
        route.shipper_holding = shipper.holding
        route.save(update_fields=["shipper_name", "shipper_holding"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_message_type_verbose_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okpo", models.BigIntegerField(blank=True, null=True, verbose_name="ОКПО")),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Грузоотправитель"),
                ),
                (
                    "holding",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Холдинг грузоотправителя",
                    ),
                ),
                (
                    "name_search",
                    models.CharField(
                        db_index=True,
                        default="",
                        editable=False,
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Грузоотправитель",
                "verbose_name_plural": "Грузоотправители",
                "ordering": ["name", "okpo"],
            },
        ),
        migrations.AddConstraint(
            model_name="shipper",
            constraint=models.UniqueConstraint(
                fields=("okpo", "inn", "name"),
                name="uniq_shipper_okpo_inn_name",
            ),
        ),
        migrations.RenameField(
            model_name="route",
            old_name="shipper",
            new_name="shipper_name",
        ),
        migrations.AddField(
            model_name="route",
            name="shipper_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.shipper",
                verbose_name="Грузоотправитель",
            ),
        ),
        migrations.RunPython(migrate_route_shippers, reverse_migrate_route_shippers),
        migrations.RemoveField(
            model_name="route",
            name="shipper_holding",
        ),
        migrations.RemoveField(
            model_name="route",
            name="shipper_name",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="shipper_link",
            new_name="shipper",
        ),
        migrations.AlterField(
            model_name="route",
            name="shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="core.shipper",
                verbose_name="Грузоотправитель",
            ),
        ),
    ]
