# Generated by Django 6.0.2 on 2026-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cargo_code_izpod',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код груза (изпод)'),
        ),
        migrations.AddField(
            model_name='route',
            name='cargo_group_cmtp',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Группа груза ЦМТП'),
        ),
        migrations.AddField(
            model_name='route',
            name='distance_belt',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Пояс дальности'),
        ),
        migrations.AddField(
            model_name='route',
            name='park_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тип парка'),
        ),
        migrations.AddField(
            model_name='route',
            name='shipment_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Категория отправки'),
        ),
        migrations.AddField(
            model_name='route',
            name='special_container_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Вид спец. контейнера'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Код маршрута (index в ИХ_ГП)'),
        ),
    ]
