# Indexes for route-analysis modal: filter by route_set + shipper (holding)
# and economics_filled (market_price_per_ton IS NOT NULL) scoped lists.
# Generated by Django 6.0.2 on 2026-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cargogroup_shipper_search_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_set', 'shipper'], name='route_set_shipper_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(condition=models.Q(('market_price_per_ton__isnull', False)), fields=['route_set', 'id'], name='route_set_economics_idx'),
        ),
    ]
