# Generated by Django 6.0.2 on 2026-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_route_enterprise_load_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='turnover_change_coef_2025',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэфф. изменения грузооборота 2025'),
        ),
        migrations.AddField(
            model_name='route',
            name='turnover_change_coef_2026',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэфф. изменения грузооборота 2026'),
        ),
        migrations.AddField(
            model_name='route',
            name='turnover_change_coef_2027',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэфф. изменения грузооборота 2027'),
        ),
        migrations.AddField(
            model_name='route',
            name='turnover_change_coef_2028',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэфф. изменения грузооборота 2028'),
        ),
        migrations.AddField(
            model_name='route',
            name='turnover_change_coef_2029',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэфф. изменения грузооборота 2029'),
        ),
        migrations.AddField(
            model_name='route',
            name='turnover_change_coef_2030',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Коэфф. изменения грузооборота 2030'),
        ),
    ]
