# Generated by Django 6.0.2 on 2026-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_cargo_category_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="fixed_retention_coefficient",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=6,
                null=True,
                verbose_name="Постоянный коэффициент сохранения",
            ),
        ),
    ]

