# Generated by Django 6.0.2 on 2026-07-13 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_route_fixed_retention_coefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteEqualizerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('base', 'Базовый'), ('user', 'Пользовательский')], default='base', max_length=8, verbose_name='Вариант')),
                ('overrides', models.JSONField(blank=True, default=dict, verbose_name='Переопределения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalizer_presets', to='core.route', verbose_name='Маршрут')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalizer_presets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пресет эквалайзера маршрута',
                'verbose_name_plural': 'Пресеты эквалайзера маршрутов',
                'constraints': [models.UniqueConstraint(fields=('user', 'route'), name='uniq_equalizer_preset_user_route')],
            },
        ),
    ]
