# Generated by Django 6.0.2 on 2026-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_route_equalizer_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_class',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Класс'),
        ),
    ]
