# Generated by Django 6.0.2 on 2026-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_scenario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='end_year',
            field=models.IntegerField(default=2035, verbose_name='Год окончания'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='start_year',
            field=models.IntegerField(default=2025, verbose_name='Год начала'),
        ),
    ]
