# Generated by Django 6.0.2 on 2026-02-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_scenario_end_year_scenario_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTDCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btd_categories', to='scenarios.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Категория базовых тарифных решений',
                'verbose_name_plural': 'Категории базовых тарифных решений',
                'ordering': ['scenario', 'position', 'id'],
                'unique_together': {('scenario', 'position')},
            },
        ),
    ]
