# Generated by Django 6.0.2 on 2026-02-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_btdcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTDCategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='scenarios.btdcategory', verbose_name='Категория')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btd_values', to='scenarios.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Значение категории базовых тарифных решений',
                'verbose_name_plural': 'Значения категорий базовых тарифных решений',
                'ordering': ['scenario', 'category', 'year'],
                'unique_together': {('scenario', 'category', 'year')},
            },
        ),
    ]
