# Generated by Django 6.0.2 on 2026-03-17

import django.db.models.deletion
from django.db import migrations, models


def backfill_scenario_route_set(apps, schema_editor):
    scenario_model = apps.get_model("scenarios", "Scenario")
    route_set_model = apps.get_model("core", "RouteSet")

    # Если наборов маршрутов нет — создаём технический.
    route_set = route_set_model.objects.order_by("id").first()
    if route_set is None:
        route_set = route_set_model.objects.create(
            name="Технический набор маршрутов",
            code="DEFAULT_ROUTE_SET",
        )

    scenario_model.objects.filter(route_set__isnull=True).update(route_set=route_set)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_routeset_route_route_uniq_route_set_route_code"),
        ("scenarios", "0005_btdcategoryvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="route_set",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="core.routeset",
                verbose_name="Набор маршрутов",
            ),
        ),
        migrations.RunPython(backfill_scenario_route_set, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="scenario",
            name="route_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="core.routeset",
                verbose_name="Набор маршрутов",
            ),
        ),
    ]

