# Generated by Django 6.0.2 on 2026-04-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0008_tariffrule_base_percent_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название набора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_sets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Набор курсов валют',
                'verbose_name_plural': 'Наборы курсов валют',
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='exchange_rate_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenarios.exchangerateset', verbose_name='Набор курсов валют'),
        ),
        migrations.CreateModel(
            name='ExchangeRateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('usd_rub', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='USD/RUB')),
                ('rate_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='scenarios.exchangerateset', verbose_name='Набор курсов')),
            ],
            options={
                'verbose_name': 'Курс валюты по году',
                'verbose_name_plural': 'Курсы валют по годам',
                'ordering': ['rate_set', 'year'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerateset',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='uniq_exchange_rate_set_author_name'),
        ),
        migrations.AddConstraint(
            model_name='exchangeratevalue',
            constraint=models.UniqueConstraint(fields=('rate_set', 'year'), name='uniq_exchange_rate_value_set_year'),
        ),
    ]
