# Generated by Django 6.0.2 on 2026-05-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0009_exchangerateset_scenario_exchange_rate_set_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InflationSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название набора")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inflation_sets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор инфляции",
                "verbose_name_plural": "Наборы инфляции",
                "ordering": ["-updated_at", "-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="scenario",
            name="inflation_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="scenarios.inflationset",
                verbose_name="Набор инфляции",
            ),
        ),
        migrations.CreateModel(
            name="InflationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год")),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Инфляция, %",
                    ),
                ),
                (
                    "inflation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="scenarios.inflationset",
                        verbose_name="Набор инфляции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инфляция по году",
                "verbose_name_plural": "Инфляция по годам",
                "ordering": ["inflation_set", "year"],
            },
        ),
        migrations.AddConstraint(
            model_name="inflationset",
            constraint=models.UniqueConstraint(
                fields=("author", "name"),
                name="uniq_inflation_set_author_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="inflationvalue",
            constraint=models.UniqueConstraint(
                fields=("inflation_set", "year"),
                name="uniq_inflation_value_set_year",
            ),
        ),
    ]
