# Generated by Django 6.0.2 on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0010_inflationset_scenario_inflation_set_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioPriceChangeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("operators", "Операторы"),
                            ("transshipment", "Перевалка"),
                            ("cost", "Себестоимость"),
                            ("market_price", "Рыночная цена"),
                            ("excise_duty", "Акциз/пошлина"),
                        ],
                        max_length=32,
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Без изменений"),
                            ("inflation", "По инфляции"),
                        ],
                        default="fixed",
                        max_length=32,
                        verbose_name="Режим изменения",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_change_settings",
                        to="scenarios.scenario",
                        verbose_name="Сценарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка изменения цены",
                "verbose_name_plural": "Настройки изменения цен",
                "ordering": ["scenario", "parameter"],
            },
        ),
        migrations.AddConstraint(
            model_name="scenariopricechangesetting",
            constraint=models.UniqueConstraint(
                fields=("scenario", "parameter"),
                name="uniq_scenario_price_change_parameter",
            ),
        ),
    ]
