# Generated by Django 6.0.2 on 2026-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0011_scenariopricechangesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='export_price_mode',
            field=models.CharField(choices=[('fixed', 'Без изменений'), ('by_fx', 'По курсу $')], default='fixed', max_length=16, verbose_name='Экспортная цена'),
        ),
    ]
