# Generated by Django 6.0.2 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0012_scenario_export_price_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="include_base_tariff_decisions",
            field=models.BooleanField(
                default=True,
                verbose_name="Учитывать базовые тарифные решения",
            ),
        ),
    ]

