# Generated by Django 6.0.2 on 2026-06-19 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_route_model_fields'),
        ('scenarios', '0013_scenario_include_base_tariff_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticitySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название набора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elasticity_sets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Набор эластичности',
                'verbose_name_plural': 'Наборы эластичности',
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ElasticityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название правила')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elasticity_rules', to='core.cargo', verbose_name='Груз')),
                ('cargo_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elasticity_rules', to='core.cargogroup', verbose_name='Группа груза')),
                ('message_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elasticity_rules', to='core.messagetype', verbose_name='Вид сообщения')),
                ('elasticity_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='scenarios.elasticityset', verbose_name='Набор эластичности')),
            ],
            options={
                'verbose_name': 'Правило эластичности',
                'verbose_name_plural': 'Правила эластичности',
                'ordering': ['elasticity_set', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='elasticity_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenarios.elasticityset', verbose_name='Набор эластичности'),
        ),
        migrations.CreateModel(
            name='ElasticityRulePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marginality', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Маржинальность')),
                ('coefficient', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Коэффициент')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='scenarios.elasticityrule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Точка эластичности',
                'verbose_name_plural': 'Точки эластичности',
                'ordering': ['rule', 'marginality', 'id'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'marginality'), name='uniq_elasticity_rule_point_marginality')],
            },
        ),
        migrations.AddConstraint(
            model_name='elasticityset',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='uniq_elasticity_set_author_name'),
        ),
    ]
