# Generated by Django 6.0.2 on 2026-06-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0018_alter_scenario_retention_coefficient_mode_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='consider_turnover_changes',
            field=models.BooleanField(default=False, verbose_name='Учитывать изменения грузооборота'),
        ),
    ]
