# Generated by Django 6.0.2 on 2026-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0020_scenario_consider_demand_elasticity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='consider_turnover_changes',
            field=models.BooleanField(default=False, verbose_name='Учитывать изменения погрузки'),
        ),
    ]
