# Generated by Django 6.0.2 on 2026-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0024_scenario_ignore_own_axles_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='retention_coefficient_mode',
            field=models.CharField(choices=[('combined', 'Комбинированный (снижение — от базы, рост — по текущей ≤1)'), ('absolute', 'По текущей маржинальности'), ('relative_to_base', 'Относительно базовой маржинальности')], default='combined', max_length=32, verbose_name='Прогноз коэффициента сохранения грузовой базы'),
        ),
    ]
